// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { GenisToken$Type } from "./GenisToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["GenisToken"]: GenisToken$Type;
    ["contracts/GenisToken.sol:GenisToken"]: GenisToken$Type;
  }

  interface ContractTypesMap {
    ["GenisToken"]: GetContractReturnType<GenisToken$Type["abi"]>;
    ["contracts/GenisToken.sol:GenisToken"]: GetContractReturnType<GenisToken$Type["abi"]>;
  }
}
