/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GenisPass__factory } from "./GenisPass__factory";
export { GenisToken__factory } from "./GenisToken__factory";
